/* ==================================================
   GLOWMART — Product Database
   ================================================== */
window.PRODUCTS = [
  { id: 1, name: 'AirPods Max 2', price: 129, oldPrice: 169, desc: 'Spatial audio, premium build quality with active noise cancellation', icon: 'fa-headphones', category: 'electronics', subcat: 'featured', tag: '-20%', rating: 4.8, reviews: 234, stock: 15, brand: 'Apple' },
  { id: 2, name: 'Organic Cotton Tee', price: 34, oldPrice: null, desc: '100% organic cotton, relaxed fit, eco-friendly', icon: 'fa-shirt', category: 'fashion', subcat: 'featured', tag: 'eco', tagColor: 'green', rating: 5.0, reviews: 189, stock: 50, brand: 'EcoWear' },
  { id: 3, name: 'Ultraboost 23', price: 89, oldPrice: 110, desc: 'Lightweight, responsive cushion, perfect for running', icon: 'fa-shoe-prints', category: 'fashion', subcat: 'featured', tag: 'hot', rating: 5.0, reviews: 412, stock: 8, brand: 'Adidas' },
  { id: 4, name: 'Zenbook S 14', price: 1499, oldPrice: null, desc: 'OLED display, Intel Core Ultra 7, 16GB RAM', icon: 'fa-laptop', category: 'electronics', subcat: 'featured', tag: 'new', tagColor: 'blue', rating: 4.9, reviews: 78, stock: 5, brand: 'ASUS' },
  { id: 5, name: 'Instax Mini 12', price: 79, oldPrice: null, desc: 'Instant film camera, pastel colors, compact design', icon: 'fa-camera', category: 'electronics', subcat: 'new', rating: 4.9, reviews: 156, stock: 22, brand: 'Fujifilm' },
  { id: 6, name: 'Smart Watch Series 10', price: 429, oldPrice: null, desc: 'GPS + Cellular, always-on display, health tracking', icon: 'fa-clock', category: 'electronics', subcat: 'new', rating: 4.7, reviews: 324, stock: 12, brand: 'Apple' },
  { id: 7, name: 'Ember Mug 2', price: 99, oldPrice: null, desc: 'Temperature control, app enabled, keeps drink warm', icon: 'fa-mug-hot', category: 'home', subcat: 'new', rating: 5.0, reviews: 98, stock: 30, brand: 'Ember' },
  { id: 8, name: 'Ergonomic Chair Pro', price: 249, oldPrice: null, desc: 'Mesh back, lumbar support, adjustable arms', icon: 'fa-chair', category: 'home', subcat: 'new', rating: 4.9, reviews: 267, stock: 10, brand: 'Herman' },
  { id: 9, name: 'Wireless Earbuds Pro', price: 159, oldPrice: 199, desc: 'Active noise cancellation, 30h battery life', icon: 'fa-headphones-simple', category: 'electronics', subcat: 'featured', tag: '-20%', rating: 4.7, reviews: 512, stock: 25, brand: 'Sony' },
  { id: 10, name: 'Minimalist Backpack', price: 69, oldPrice: null, desc: 'Water-resistant, USB charging port, laptop sleeve', icon: 'fa-bag-shopping', category: 'fashion', subcat: 'new', tag: 'new', tagColor: 'blue', rating: 4.8, reviews: 145, stock: 40, brand: 'Bellroy' },
  { id: 11, name: 'MacBook Air M3', price: 1099, oldPrice: 1299, desc: 'M3 chip, 13.6" Retina display, 18h battery', icon: 'fa-laptop-code', category: 'electronics', subcat: 'featured', tag: 'sale', rating: 4.9, reviews: 189, stock: 7, brand: 'Apple' },
  { id: 12, name: 'iPhone 16 Pro', price: 999, oldPrice: null, desc: 'A18 Pro chip, 48MP camera, titanium body', icon: 'fa-mobile-screen', category: 'electronics', subcat: 'new', tag: 'new', tagColor: 'blue', rating: 5.0, reviews: 432, stock: 18, brand: 'Apple' },
  { id: 13, name: 'Yoga Mat Premium', price: 45, oldPrice: 65, desc: 'Non-slip, eco-friendly, 6mm thick', icon: 'fa-spa', category: 'sports', subcat: 'featured', tag: '-30%', rating: 4.6, reviews: 234, stock: 60, brand: 'Liforme' },
  { id: 14, name: 'Gaming Keyboard RGB', price: 89, oldPrice: null, desc: 'Mechanical switches, RGB backlit, programmable', icon: 'fa-keyboard', category: 'gaming', subcat: 'new', rating: 4.7, reviews: 189, stock: 35, brand: 'Razer' },
  { id: 15, name: 'Sunglasses Polarized', price: 79, oldPrice: 119, desc: 'UV400 protection, polarized lens, unisex', icon: 'fa-glasses', category: 'fashion', subcat: 'featured', tag: '-33%', rating: 4.5, reviews: 98, stock: 45, brand: 'RayBan' },
  { id: 16, name: 'Coffee Maker Deluxe', price: 149, oldPrice: null, desc: 'Programmable, 12-cup capacity, thermal carafe', icon: 'fa-mug-saucer', category: 'home', subcat: 'new', rating: 4.8, reviews: 267, stock: 20, brand: 'Cuisinart' },
  { id: 17, name: 'Bluetooth Speaker', price: 69, oldPrice: 99, desc: '360° sound, waterproof, 24h battery', icon: 'fa-volume-high', category: 'electronics', subcat: 'featured', tag: '-30%', rating: 4.7, reviews: 345, stock: 28, brand: 'JBL' },
  { id: 18, name: 'Skincare Set', price: 89, oldPrice: null, desc: 'Complete routine: cleanser, serum, moisturizer', icon: 'fa-spa', category: 'beauty', subcat: 'new', rating: 4.9, reviews: 156, stock: 50, brand: 'The Ordinary' },
  { id: 19, name: 'Wireless Mouse', price: 34, oldPrice: null, desc: 'Ergonomic, silent click, 12-month battery', icon: 'fa-computer-mouse', category: 'electronics', subcat: 'new', rating: 4.6, reviews: 234, stock: 100, brand: 'Logitech' },
  { id: 20, name: 'Fitness Tracker', price: 79, oldPrice: 99, desc: 'Heart rate, sleep tracking, 7-day battery', icon: 'fa-heart-pulse', category: 'sports', subcat: 'featured', tag: '-20%', rating: 4.5, reviews: 178, stock: 40, brand: 'Fitbit' },
  { id: 21, name: 'Desk Lamp LED', price: 49, oldPrice: null, desc: 'Touch control, 3 color modes, USB charging', icon: 'fa-lightbulb', category: 'home', subcat: 'new', rating: 4.7, reviews: 89, stock: 55, brand: 'TaoTronics' },
  { id: 22, name: 'Novel: The Silent Patient', price: 19, oldPrice: 29, desc: 'Bestseller thriller, paperback edition', icon: 'fa-book', category: 'books', subcat: 'featured', tag: '-34%', rating: 4.8, reviews: 567, stock: 100, brand: 'Penguin' },
  { id: 23, name: 'Running Shoes', price: 119, oldPrice: null, desc: 'Breathable mesh, cushion sole, lightweight', icon: 'fa-shoe-prints', category: 'sports', subcat: 'new', rating: 4.6, reviews: 234, stock: 30, brand: 'Nike' },
  { id: 24, name: 'Perfume Gift Set', price: 129, oldPrice: 179, desc: '3 premium fragrances in luxury box', icon: 'fa-spray-can', category: 'beauty', subcat: 'featured', tag: '-28%', rating: 4.9, reviews: 123, stock: 25, brand: 'Chanel' }
];
